### ISSUE TITLE
fail2ban    | WARNING: no logs are available with the 'db' log driver

### ISSUE THREAD

**Issue by GerritKuilder** [sosandroid/docker-fail2ban-synology#2]
I am getting the above error message when I run docker-compose -f docker-compose_fail2ban.yml up

fail2ban    | WARNING: no logs are available with the 'db' log driver

Any tips in this regards?

Thanks,

Gerrit Kuilder

**Comment by sosandroid** [comment]
I have the same one. Just a warn
Does your ban tests work

**Comment by GerritKuilder** [comment]
I don't see it doing anything

**Comment by sosandroid** [comment]
The issue may come from the jail definition

**Comment by GerritKuilder** [comment]
Have given up on docker for nginx etc...
