### ISSUE TITLE
Banned but not blocking...

### ISSUE THREAD

**Issue by Bogey** [sosandroid/docker-fail2ban-synology#4]
Hi, I could really use your help.
NGINX Proxy Manager reports the correct IP address, but I can still access the page.
So I've tested with VPN and banned my IP address manually, checking iptables shows the following:
`admin@DS1621:~$ sudo iptables -S | grep f2b
-N f2b-authelia
-N f2b-nginx-proxy-manager
-A INPUT -p tcp -j f2b-nginx-proxy-manager
-A INPUT -p tcp -j f2b-authelia
-A f2b-authelia -s 213.152.188.22/32 -j DROP
-A f2b-authelia -j RETURN
-A f2b-nginx-proxy-manager -s 213.152.188.22/32 -j DROP
-A f2b-nginx-proxy-manager -j RETURN`
If I change the jail.d action to
`action = iptables-allports[name=nginx-proxy-manager,chain="DOCKER-USER"]` then, obviously, INPUT changes to DOCKER-USER, but no success either. Same goes for FORWARD.

NGINX Proxy Manager, Authelia, Fail2ban are all in containers.
NGINX Proxy Manager is on default bridge network. Authelia has it's own bridge network. fail2ban is set to host.

**Comment by Bogey** [comment]
Ok fixed it. Using Cloudflare as a proxy requires a 'cloudflare' action in f2b. If Cloudflare is used for DNS only then it'll work with the 'iptables-allports' action.

**Comment by sosandroid** [comment]
Thanks for the update

**Comment by edoubleoo** [comment]
Hi Bogey, 

I have been having a similar issue.

Our docker install of F2B is located behind our firewall, with all exterior accessible services secured behind a reverse proxy at site and a Cloudflare proxy. At present, F2B can read the Cloudflare IP address incoming and block the potential threat locally, but without an action call to the Cloudflare firewall to request the same address IP is banned, I'm left at a major disadvantage. 

Could you elaborate on implementing the Cloudflare action, especially when using proxied rather than DNS only? 

Did you implement the action to "etc/fail2ban/jail.local"?

Thanks

**Comment by Bogey** [comment]
etc/fail2ban/jail.local contains all Cloudflare IP addresses:
```
[DEFAULT]
# ban IP on CloudFlare & send an e-mail with whois report and relevant log lines
# to the destemail.
action_cf_mwl = cloudflare[cfuser="%(cfemail)s", cftoken="%(cfapikey)s", cfzone="%(cfzoneid)s"]
                %(mta)s-whois-lines[sender="%(sender)s", dest="%(destemail)s", logpath="%(logpath)s", chain="%(chain)s"]

# "ignoreip" can be an IP address, a CIDR mask or a DNS host. Fail2ban will not
# ban a host which matches an address in this list. Several addresses can be
# defined using space separator.
ignoreip = 127.0.0.1/8 172.16.0.0/12 192.168.0.0/24 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 172.64.0.0/13 131.0.72.0/22 104.16.0.0/13 104.24.0.0/14 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2a06:98c0::/29 2c0f:f248::/32

# as an example I include this:
[nginx-http-auth]
enabled  = true
filter   = nginx-http-auth
port     = http,https
logpath  = /logs/npm/error.log
findtime = 15m
bantime = 15m
maxretry = 5
action = iptables-allports[name=nginx-http-auth]
         %(action_cf_mwl)s
cfemail  = youremail@gmail.com
cfapikey = replace_with_your_token
cfzoneid = user
```
Then I have in action.d folder the file cloudflare.local (see [Archive 2.zip](https://github.com/sosandroid/docker-fail2ban-synology/files/6946163/Archive.2.zip) ) and as an example I've included authelia.conf (you put that one in jail.d folder).
By the way: I've adjusted cloudflare.local so that it supports zones.

I hope this helps.
